"""A curated list of common business / industry types, grouped by category.

Used to populate the searchable multi-select industry picker in the web UI.
The user can always add a value that isn't on this list — it's a convenience,
not a restriction — or pick "Any" to target all industries.
"""

from __future__ import annotations

BUSINESS_TYPE_GROUPS: dict[str, list[str]] = {
    "Professional services": [
        "Law firms",
        "Accounting firms",
        "Bookkeeping services",
        "Tax preparation services",
        "Management consulting",
        "Marketing agencies",
        "Advertising agencies",
        "Public relations firms",
        "Architecture firms",
        "Engineering firms",
        "Surveying firms",
        "Recruiting & staffing agencies",
        "Translation services",
        "Notary & title services",
        "Insurance agencies",
        "Financial advisors",
        "Wealth management firms",
        "Mortgage brokers",
        "Real estate brokerages",
        "Property management companies",
        "Commercial real estate firms",
    ],
    "Health & wellness": [
        "Dental practices",
        "Orthodontists",
        "Medical clinics",
        "Family medicine practices",
        "Pediatric clinics",
        "Dermatology clinics",
        "Optometry & eye care",
        "Chiropractic clinics",
        "Physical therapy clinics",
        "Mental health practices",
        "Veterinary clinics",
        "Med spas",
        "Day spas",
        "Massage therapy",
        "Gyms & fitness studios",
        "Yoga & pilates studios",
        "Nutritionists & dietitians",
        "Home health care agencies",
        "Assisted living facilities",
        "Pharmacies (independent)",
    ],
    "Food & hospitality": [
        "Restaurants",
        "Cafes & coffee shops",
        "Bakeries",
        "Bars & breweries",
        "Wineries",
        "Food trucks",
        "Catering companies",
        "Hotels & motels",
        "Bed & breakfasts",
        "Event venues",
        "Wedding planners",
        "Event planning companies",
    ],
    "Retail & e-commerce": [
        "Boutique retail stores",
        "Clothing & apparel stores",
        "Jewelry stores",
        "Furniture stores",
        "Home goods stores",
        "Hardware stores",
        "Garden centers & nurseries",
        "Pet stores",
        "Bookstores",
        "Specialty food shops",
        "E-commerce brands",
        "Online subscription boxes",
    ],
    "Trades & home services": [
        "General contractors",
        "Home builders",
        "Remodeling & renovation",
        "Plumbing services",
        "HVAC services",
        "Electrical services",
        "Roofing companies",
        "Painting contractors",
        "Flooring contractors",
        "Landscaping & lawn care",
        "Pest control services",
        "Cleaning & janitorial services",
        "Pool services",
        "Moving companies",
        "Garage door services",
        "Solar installers",
        "Locksmiths",
        "Handyman services",
        "Window & door installers",
    ],
    "Automotive": [
        "Auto repair shops",
        "Auto body shops",
        "Car dealerships",
        "Tire shops",
        "Car wash & detailing",
        "Towing services",
        "Auto parts stores",
    ],
    "Technology": [
        "Software companies (SaaS)",
        "IT services & managed service providers",
        "Web design agencies",
        "App development studios",
        "Cybersecurity firms",
        "Data & analytics firms",
        "Cloud consulting firms",
        "Hardware & electronics manufacturers",
    ],
    "Manufacturing & industrial": [
        "Manufacturers",
        "Industrial equipment suppliers",
        "Wholesale distributors",
        "Packaging companies",
        "Printing & signage companies",
        "Metal fabrication shops",
        "Machine shops",
        "Logistics & freight companies",
        "Warehousing companies",
    ],
    "Education & nonprofit": [
        "Private schools",
        "Preschools & daycares",
        "Tutoring centers",
        "Trade & vocational schools",
        "Online course creators",
        "Nonprofits & charities",
        "Religious organizations",
        "Membership associations",
    ],
    "Creative & media": [
        "Photography studios",
        "Videography & film production",
        "Graphic design studios",
        "Interior design firms",
        "Music & recording studios",
        "Publishing companies",
        "Podcast networks",
    ],
    "Personal & local services": [
        "Hair salons",
        "Barbershops",
        "Nail salons",
        "Tattoo & piercing studios",
        "Dry cleaners & laundromats",
        "Childcare services",
        "Pet grooming & boarding",
        "Tailors & alterations",
        "Travel agencies",
        "Security services",
        "Funeral homes",
    ],
    "Agriculture & outdoors": [
        "Farms & ranches",
        "Vineyards",
        "Florists",
        "Tree services & arborists",
        "Outdoor recreation outfitters",
    ],
}

# Flat list kept for anything that doesn't care about grouping.
BUSINESS_TYPES: list[str] = [t for group in BUSINESS_TYPE_GROUPS.values() for t in group]
